core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    # books
    path('book', views.book_list, name="book_list"),
    path('book/create/', views.book_create, name="book_create"),

    path('book/create/<int:pk>', views.copy_create, name="book_copy"),
    path('book/copy/remove/<int:pk>', views.copy_remove, name="copy_remove"),
    path('book/copy/edit/<int:pk>', views.copy_edit, name="copy_edit"),
    
    path('book/<int:pk>', views.book_detail, name="book_detail"),
    path('book/<int:pk>/update', views.book_update, name="book_update"),
    path('book/<int:pk>/delete', views.book_delete, name="book_delete"),
    path('book/delete/<int:pk>/confirm', views.book_delete_confirmation, name="book_delete_confirmation"),

    # membership
    path('member', views.member_list, name="member_list"),
    path('member/create', views.member_create, name="member_create"),
    path('member/<int:pk>', views.member_detail, name="member_detail"),
    path('member/<int:pk>/update', views.member_update, name="member_update"),
    path('member/delete/<int:pk>', views.delete_member_confirmation, name="delete_member"),

    # borrow a book
    path('member/<int:pk>/borrow', views.book_borrow, name="book_borrow"),

    # notification
    path('notification', views.notification, name="notification"),
    path('notification/clear', views.notification_clear, name="notification_clear"),

    # profile
    path('profile', views.profile, name="profile"),
    path('profile/members', views.profile_member, name="profile_member"),
    path('profile/books', views.profile_book, name="profile_book"),
    path('profile/change_password', views.profile_password_change, name="profile_password_change"),

]

workbench/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


# from core import views as core_views
# from django.conf.urls import handler404, handler500

urlpatterns = [
    # path('admin/', admin.site.urls),

    path('', include('account.urls', namespace='account')),

    path('book', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# handler404 = core_views.error_404
# handler500 = core_views.error_500

core/models.py
from random import choices
from re import T
from django.db import models
from datetime import datetime
from account.models import User

# Create your models here.


class Membership(models.Model):
    HALLS = (
        ("Abigail", "Abigail"),
        ("Abraham", "Abraham"),
        ("Daniel", "Daniel"),
        ("Deborah", "Deborah"),
        ("Dorcas", "Dorcas"),
        ("Isaac", "Isaac"),
        ("Joseph", "Joseph"),
        ("Sarah", "Sarah"),
    )

    COLLEGE = (
        ("Accounting", "Accounting"),
        ("Agricultural Economics", "Agricultural Economics"),
        ("Agricultural Extension & Rural Development", "Agricultural Extension & Rural Development"),
        ("Agriculture & Exosystem Engineering", "Agriculture & Exosystem Engineering"),
        ("Animal Science", "Animal Science"),
        ("Biochemistry", "Biochemistry"),
        ("Business Administration", "Business Administration"),
        ("Chemical Engineering", "Chemical Engineering"),
        ("Civil Engineering", "Civil Engineering"),
        ("Computer Science", "Computer Science"),
        ("Crop Science", "Crop Science"),
        ("Economics", "Economics"),
        ("Electrical and Information Engineering", "Electrical and Information Engineering"),
        ("Food Science and Nutrition / Microbiology", "Food Science and Nutrition / Microbiology"),
        ("Industrial Chemistry", "Industrial Chemistry"),
        ("International Relations", "International Relations"),
        ("Mass Communication", "Mass Communication"),
        ("Mathematics", "Mathematics"),
        ("Mechanical Engineering", "Mechanical Engineering"),
        ("Mechatronics Engineering ", "Mechatronics Engineering"),
        ("Political Science", "Political Science"),
        ("Sociology", "Sociology"),
        ("Soil Science", "Soil Science"),    
    )

    LEVEL = (
        ("100", "100"),
        ("200", "200"),
        ("300", "300"),
        ("400", "400"),
        ("500", "500"),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    gender = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=15)
    reg = models.CharField(max_length=50, null=True, blank=True)
    current_level = models.CharField(max_length=2000, choices=LEVEL, null=True, blank=True)

    # address
    residence_hall = models.CharField(max_length=20, choices=HALLS, null=True, blank=True)
    room = models.CharField(max_length=5, null=True, blank=True)

    # college
    department = models.CharField(max_length=500, null=True, blank=True, choices=COLLEGE)

    date_joined = models.DateTimeField(default=datetime.now)

    def __str__(self):
        if self.reg:
            return self.reg
        else:
            return self.name


# including books
class Book(models.Model):
    title = models.CharField(max_length=500)
    author = models.CharField(max_length=200)
    quantity = models.PositiveIntegerField(default=0)
    date_created = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.title


class Copy(models.Model):
    book = models.ForeignKey(Book, related_name="copies", on_delete=models.CASCADE)
    unique_number = models.CharField(max_length=1000)

    def __str__(self):
        return self.unique_number


# Borrowing books
class BorrowedBook(models.Model):
    book = models.ForeignKey(Book, related_name="borrowed_book", on_delete=models.CASCADE)
    copy = models.ForeignKey(Copy, related_name="borrowed_book_copy", on_delete=models.CASCADE)
    borrower = models.ForeignKey(Membership, related_name="borrowed_book", on_delete=models.CASCADE)
    date_borrowed = models.DateField(default=datetime.now)
    date_to_be_returned = models.DateField()


class Notification(models.Model):
    heading = models.CharField(max_length=250)
    message = models.CharField(max_length=5000)

    date_created = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.account.username


class ReturnCount(models.Model):
    member = models.OneToOneField(Membership, on_delete=models.CASCADE)
    count = models.IntegerField()

    def __str__(self):
        return f"{self.member.name} is due" 

core/forms.py
from django import forms
from .models import Book, Membership, BorrowedBook


class BookCreationForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = (
            "title",
            "author",
        )



class MembershipCreationForm(forms.ModelForm):

    CHOICES = [('male','male'),('female','female')]
    gender = forms.CharField(label='What is your gender?', widget=forms.RadioSelect(choices=CHOICES))

    class Meta:
        model = Membership
        fields = (
            "name",
            "email",
            "phone_number",
            "reg",
            "current_level",
            "department",
            "residence_hall",
            "room",
        )



class BookBorrowingForm(forms.ModelForm):
    class Meta:
        model = BorrowedBook
        fields = {
            "book",
        }

core/views.py
from datetime import datetime, timedelta
from email import message
from itertools import count
from operator import le
from turtle import left
from django.shortcuts import render, redirect

from .models import BorrowedBook, Membership, Notification, Book, Copy, ReturnCount
from .forms import BookCreationForm, MembershipCreationForm, BookBorrowingForm
from django.contrib import messages
from account.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login

# Create your views here.

'''members management'''
@login_required
def member_list(request):
    member = Membership.objects.all()
    borrowedbooks = BorrowedBook.objects.all()

    if request.method == 'POST':
        if request.POST.get('search'):
            for person in member:
                search = request.POST.get('search')
                if person.reg == search:
                    return redirect('core:member_detail', person.id)
                elif person.email == search:
                    return redirect('core:member_detail', person.id)


    days_left = ""
    
    for m in member:
        if m.borrowed_book.exists():
            owing_book = BorrowedBook.objects.get(borrower=m)

            '''Getting the borrow period'''
            current_date = datetime.now()
            days = owing_book.date_to_be_returned - current_date.date()
            # days = owing_book.date_to_be_returned - (current_date.date() + timedelta(days=7) )

            days_left = days.days


            if ReturnCount.objects.filter(member=m).exists():
                days_left = days_left - 1

            if days_left == 0:
                count = ReturnCount.objects.create(member=m, count=days_left)
                count.save

                notification_heading = "Book Return Due"
                notification_message = f"'{m.name}' has reached the book return date for '{owing_book.book}'( {owing_book.copy} )"
                alert = Notification.objects.create(heading=notification_heading, message=notification_message)
                alert.save()

    return render(request, "core/member-list.html", {"member": member, "books": borrowedbooks, "days": days_left})

@login_required
def member_create(request):
    current_user = request.user

    form = MembershipCreationForm()
    if request.method == "POST":
        form = MembershipCreationForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            number = form.cleaned_data["phone_number"]
            reg = form.cleaned_data["reg"]
            level = form.cleaned_data['current_level']
            gender = form.cleaned_data['gender']
            hall = form.cleaned_data['residence_hall']
            room = form.cleaned_data['room']
            department = form.cleaned_data['department']

            new_member = Membership.objects.create(user=current_user, name=name, email=email, phone_number=number,
                                                    reg=reg, current_level=level, gender=gender,
                                                    residence_hall=hall, room=room, 
                                                    department=department)
            new_member.save()

            notification_heading = "Membership Creation"
            notification_message = f"Membership for {name} created successfully by {current_user.username}"
            alert = Notification.objects.create(heading=notification_heading, message=notification_message)
            alert.save()

            messages.success(request, "Member added successfully")
            return redirect("core:member_list")
        else:
            messages.info(request, "There is a problem in your form!")
            return redirect("core:member_create")

    return render(request, "core/member-create.html", {"form": form})

@login_required
def member_detail(request, pk):

    member = Membership.objects.get(id=pk)

    days_left = ""

    owing_book = []
    if member.borrowed_book.exists():
        owing_book = BorrowedBook.objects.get(borrower=member)

        '''Getting the borrow period'''
        current_date = datetime.now()
        days = owing_book.date_to_be_returned - current_date.date() 
        # days = owing_book.date_to_be_returned - (current_date.date() + timedelta(days=7) )

        days_left = days.days

        if ReturnCount.objects.filter(member=member).exists():
                days_left = days_left - days_left
     


    if request.method == "POST":    
        if request.POST.get("returnBook"):
            owing_book.delete()

            notification_heading = "Book Returning"
            notification_message = f"{member.name} returned '{owing_book.book.title}': {owing_book.copy.unique_number}"
            alert = Notification.objects.create(heading=notification_heading, message=notification_message)
            alert.save()

            if ReturnCount.objects.filter(member=member).exists():
                counting = ReturnCount.objects.get(member=member)
                counting.delete()

            messages.info(request, 'Book has being returned')
            return redirect("core:member_detail", member.id)

    if request.method == "POST":
        if request.POST.get("remove"):
            member.delete()

            messages.success(request, "Membership terminated successfully")
            return redirect("core:member_list")


    return render(request, "core/member-detail.html", {"member": member, "owing": owing_book, "days_left": days_left})


@login_required
def member_update(request, pk):
    member = Membership.objects.get(id=pk)

    form = MembershipCreationForm(instance=member)
    if request.method == "POST":
        form = MembershipCreationForm(request.POST, instance=member)
        if form.is_valid():
            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            number = form.cleaned_data["phone_number"]
            reg = form.cleaned_data["reg"]
            level = form.cleaned_data['current_level']
            gender = form.cleaned_data['gender']
            hall = form.cleaned_data['residence_hall']
            room = form.cleaned_data['room']
            department = form.cleaned_data['department']

            member.name = name
            member.email = email
            member.phone_number = number
            member.reg = reg
            member.current_level = level
            member.gender = gender
            member.residence_hall = hall
            member.room = room
            member.department = department

            member.save()


            messages.success(request, "Member data updated successfully!")
            return redirect('core:member_detail', member.id)

    return render(request, "core/member_update.html", {"member": member, "form": form})


@login_required
def delete_member_confirmation(request, pk):
    member = Membership.objects.get(id=pk)

    if request.method == "POST":
        password =  request.POST.get('Password')

        if request.user.is_authenticated:
            user = User.objects.get(username=request.user.username)

            if user.check_password(password):
                member.delete()

                messages.success(request, "Membership terminated successfully")
                return redirect("core:member_list")
                
            else:
                messages.info(request, "Invalid Password")
                return redirect('core:delete_member', member.id)

    return render(request, 'core/member_delete.html', {"member": member})


@login_required
def book_borrow(request, pk):

    book = Book.objects.all()
    member = Membership.objects.get(id=pk)
    form = BookBorrowingForm()

    if request.method == "POST":
        form = BookBorrowingForm(request.POST)
        if form.is_valid():
            book_name = form.cleaned_data["book"]
            unique_num = request.POST["unique_num"]
            date = datetime.now()
            return_date = date + timedelta(days=7)

            print(return_date)

            if return_date:     
                print(return_date)      

                if Book.objects.filter(title=book_name).exists():
                    the_book = Book.objects.get(title=book_name)

                    if Copy.objects.filter(unique_number=unique_num):
                        book_copy = Copy.objects.get(unique_number=unique_num)

                        if the_book == book_copy.book:

                            if BorrowedBook.objects.filter(copy=book_copy.id).exists():
                                messages.info(request, "Book with that serial number has been borrowed")
                                return redirect("core:book_borrow", member.id)
                            else:
                                borrow_book = BorrowedBook.objects.create(book=book_name, copy=book_copy, 
                                                                            borrower=member, date_to_be_returned=return_date)

                                borrow_book.save()

                                notification_heading = "Book Borrowing"
                                notification_message = f"'{member.name}' borrowed '{book_name}' with serial number '{book_copy}'"
                                alert = Notification.objects.create(heading=notification_heading, message=notification_message)
                                alert.save()

                                messages.success(request, "Book borrowed successfully")
                                return redirect("core:member_detail", member.id)
                        else:
                            messages.info(request, "Book doesn't have such serial number")
                            return redirect("core:book_borrow", member.id)
                    else:

core/templates/core/book-delete.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .delete-btn button{
        margin-right: 20px;
    }
    .alert{
        height: 40px;
    }
    .alert svg{
        width: 20px;
    }
    .alert svg{
        margin-left: 28%;
    }
    .text{
        margin-left: 10px;
    }
</style>

<div class="delete-confirmation">
    {% if optional > 0 %}
        <h2>Deleting "{{ book.title }}" will also remove all copies</h2>
        <hr>
        
        <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div class="text">
                A copy of this book has being borrowed so it can't be deleted
            </div>
        </div>
    {% else %}
        <h2>Deleting "{{ book.title }}" will also remove all copies</h2>
        <hr>

        <form method="post">
            {% csrf_token %}
            
            <div class="delete-btn">
                <button class="btn btn-success", name="confirmDelete", value="confirmDelete">Confirm</button>
                <a href="{% url 'core:book_detail' book.id %}"><input type="button" class="btn btn-danger", value="Decline"></a>
            </div>    
        </form>
    {% endif %}
</div>

{% endblock content %}

core/templates/core/book-detail2.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<style type="text/css">
    .alert{
        height: 40px;
        width: 50%;
        display: flex;
        justify-content: center;
    }
    .alert svg{
        width: 20px;
    }
    .text{
        margin-left: 10px;
    }
    .book-detail{
        display: flex;
        margin-top: 10px;
    }
    .book-quantity{
        margin-left: 2%;
    }
    .serial-heading{
        font-size: 30px;
    }
    .book-quantity-list li{
        font-size: 20px;
        list-style: none;
    }
    .card-header button{
        margin-left: 13px;
    }
    .book-copy{
        font-weight: 600;
        margin-right: 5px;
    }
    .book-copy a{
        text-decoration: none;
        color: rgb(29, 108, 173);
    }
    .list-group-item{
        display: flex;
    }
    .list-group-item button{
        margin-left: 10px;
    }
    .list-group-item a{
        margin-left: 10px;
    }
</style>

<h2>Book: {{ book.title }}</h2>
<hr><br>


{% for message in messages %}
<div class="alert alert-success d-flex align-items-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
    <div class="text">
        {{ message }}
    </div>
</div>
{% endfor %}


<div class="book-detail">

    <div class="card mb-3" style="height: 10%;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{% static 'assets/img/open-book.png' %}" class="img-fluid rounded-start" width="400">
            </div>

            <div class="col-md-8">

                <div class="card-body">

                    <h3 class="card-title ">Author: {{ book.author }}</h3><hr>

                    <h3 class="card-text"><small class="text-muted">Total Quantity: {{ total_quantity }}</small></h3>
                    <h3 class="card-text"><small class="text-muted">Borrowed: {{ borrowed_book_amount }}</small></h3>

                    <div class="d-grid gap-3 d-md-flex justify-content-md-end">

                        <a href="{% url 'core:book_update' book.id %}"><button class="btn btn-primary me-md-2" type="button">Update</button></a>
                        
                        {% if optional > 0 %}
                            <button class="btn btn-secondary" type="button">Delete</button>
                        {% else %}

                            <a href="{% url 'core:book_delete' book.id %}"><button class="btn btn-danger" type="button">Delete</button></a>
                        {% endif %}

                    </div>

                </div>
            </div>
        </div>
    </div>
   
    <!-- To get all the book serial numbers available -->
    <div class="book-quantity">
        <div class="card" style="width: 23rem;">


            <div class="card-header">
                <form method="post">
                    {% csrf_token %}
                    <button class="btn btn-secondary btn-sm" name="addCopy" value="addCopy">Add copies</button>
                </form>
            </div>

            <!-- To get borrowed books or not -->
            {% for i in unique %}
                {% if i.book == book %}
                    <ul class="list-group list-group-flush">

                        {% if i in books %}
                            <li class="list-group-item">
                                <div class="book-copy">
                                    PSGL: {{ i.unique_number }} 
                                    
                                    {% for copy in copy_id %}
                                        {% if copy.copy.unique_number == i.unique_number %}
                                            <a href="{% url 'core:member_detail' copy.borrower.id %}">
                                                ( borrowed )
                                            </a>
                                        {% endif %}
                                    {% endfor %}
                                </div>
        
                                <input type="button" class="btn btn-secondary btn-sm" value="Remove">
                            </li>
                        {% else %}
                            <li class="list-group-item">
                                <div class="book-copy">
                                    PSGL: {{ i.unique_number }} ( available )
                                </div>
                                
                                <a href="{% url 'core:copy_edit' i.id %}"><input type="button" class="btn btn-primary btn-sm" value="Edit"></a>
                                <a href="{% url 'core:copy_remove' i.id %}"><input type="button" class="btn btn-danger btn-sm" value="Remove"></a>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>


{% endblock content %}

core/templates/core/book-list.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .alert{
        height: 40px;
    }
    .alert svg{
        width: 20px;
    }
    .alert svg{
        margin-left: 40%;
    }
    .text{
        margin-left: 10px;
    }
    td a{
        text-decoration: none;
        color: black;
    }
    .top{
        display: flex;
        justify-content: space-between;
    }
    .top h2{
        position: relative;
        top: 30px;
    }
    .create-btn{
        position: relative;
        top: 30px;
    }
  
</style>

<div class="heading">
    <div class="top">
        <h2>List of books</h2>
        

        {% if book %}
            <div class="search">
                <form method="post">
                    {% csrf_token %}
        
                    <div class="form-floating mb-1">
                        <input type="text" name="search" class="form-control", placeholder="Search members" id="floatingInput">
                        <label for="floatingInput">Search books</label>
                    </div>
                </form>
            </div>
        {% endif %}
    
        <div class="create-btn">
            <a href="{% url 'core:book_create' %}">
                <button class="btn btn-primary">
                   Add Book
                   <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-book-fill" viewBox="0 0 16 16">
                    <path d="M8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
                  </svg>
                </button>
            </a>
        </div>
    </div>
    <hr>
</div>

    

    {% for message in messages %}
        <div class="alert alert-success d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
            <div class="text">
                {{ message }}
            </div>
        </div>
    {% endfor %}


    <div class="row row-cols-1 row-cols-md-5 g-0">

        <table class="table table-striped">
            
            <tr>
                <th>
                    Title
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
                        <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
                    </svg>
                </th>

                <th>
                    Author
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                        <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    </svg>
                </th>

                <th>Copies</th>

                <th>Borrowed</th>
            </tr>

            {% for book in book %}
            <tr>
                <td>
                    <a href="{% url 'core:book_detail' book.id %}">
                        {{ book.title }}
                    </a>
                </td>

                <td>
                    <a href="{% url 'core:book_detail' book.id %}">
                        {{ book.author }}
                    </a>
                </td>

                <td>{{ book.quantity }}</td>

                {% if book.borrowed_book.exists %}
                    <td>{{ book.borrowed_book.count }}</td>
                {% else %}
                    <td>0</td>
                {% endif %}
            </tr>
            {% endfor %}
            
        </table>             
    </div>

{% endblock content %}

core/templates/core/book_delete_confirmation.html
{% extends 'profile/dashboard.html' %}

{% block content %}

<style type="text/css">
    .change-password-form{
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    .change-password-form input{
        width: 300px;
        text-align: center;
    }
    .alert{
        height: 40px;
    }
    .alert svg{
        width: 20px;
    }
    .alert svg{
        margin-left: 43%;
    }
    .text{
        margin-left: 10px;
    }
</style>


<h1 style="text-align: center;">Confirm your password</h1>
<hr>


{% for message in messages %}
<div class="alert alert-danger d-flex align-items-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
    <div class="text">
        {{ message }}
    </div>
</div>
{% endfor %}


<div class="change-password-form">
    <form method="post">
        {% csrf_token %}
    
        <input type="password", name="Password", placeholder="Password" class="textinput textInput form-control">
        <br>

        <input type="submit", value="Confirm" class="btn btn-success">
        <br><br>

        <a href="{% url 'core:book_detail' book.id %}"><input type="button" value="Cancel" class="btn btn-danger"></a>
    </form>
</div>

{% endblock content %}

core/templates/core/password_confirmation.html
{% extends 'profile/dashboard.html' %}

{% block content %}

<style type="text/css">
    .change-password-form{
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    .change-password-form input{
        width: 300px;
        text-align: center;
    }
    .alert{
        height: 40px;
    }
    .alert svg{
        width: 20px;
    }
    .alert svg{
        margin-left: 43%;
    }
    .text{
        margin-left: 10px;
    }
</style>


<h1 style="text-align: center;">Confirm your password</h1>
<hr>


{% for message in messages %}
<div class="alert alert-danger d-flex align-items-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
    <div class="text">
        {{ message }}
    </div>
</div>
{% endfor %}


<div class="change-password-form">
    <form method="post">
        {% csrf_token %}
    
        <input type="password", name="Password", placeholder="Password" class="textinput textInput form-control">
        <br>

        <input type="submit", value="Confirm" class="btn btn-success">
        <br><br>

        <a href="{% url 'core:notification' %}"><input type="button" value="Cancel" class="btn btn-danger"></a>
    </form>
</div>

{% endblock content %}