core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    # books
    path('book', views.book_list, name="book_list"),
    path('book/create/', views.book_create, name="book_create"),

    path('book/create/<int:pk>', views.copy_create, name="book_copy"),
    path('book/copy/remove/<int:pk>', views.copy_remove, name="copy_remove"),
    path('book/copy/edit/<int:pk>', views.copy_edit, name="copy_edit"),
    
    path('book/<int:pk>', views.book_detail, name="book_detail"),
    path('book/<int:pk>/update', views.book_update, name="book_update"),
    path('book/<int:pk>/delete', views.book_delete, name="book_delete"),
    path('book/delete/<int:pk>/confirm', views.book_delete_confirmation, name="book_delete_confirmation"),

    # membership
    path('member', views.member_list, name="member_list"),
    path('member/create', views.member_create, name="member_create"),
    path('member/<int:pk>', views.member_detail, name="member_detail"),
    path('member/<int:pk>/update', views.member_update, name="member_update"),
    path('member/delete/<int:pk>', views.delete_member_confirmation, name="delete_member"),

    # borrow a book
    path('member/<int:pk>/borrow', views.book_borrow, name="book_borrow"),

    # notification
    path('notification', views.notification, name="notification"),
    path('notification/clear', views.notification_clear, name="notification_clear"),

    # profile
    path('profile', views.profile, name="profile"),
    path('profile/members', views.profile_member, name="profile_member"),
    path('profile/books', views.profile_book, name="profile_book"),
    path('profile/change_password', views.profile_password_change, name="profile_password_change"),

]

workbench/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


# from core import views as core_views
# from django.conf.urls import handler404, handler500

urlpatterns = [
    # path('admin/', admin.site.urls),

    path('', include('account.urls', namespace='account')),

    path('book', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# handler404 = core_views.error_404
# handler500 = core_views.error_500

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/footers/">

    <link rel="stylesheet" href="{% static 'assets/js/bootstrap.bundle.min.js' %}">
    <link rel="stylesheet" href="{% static 'assets/js/sidebars.js' %}">

    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sidebars/">

    <link rel="stylesheet" href="{% static 'assets/css/sidebars.css' %}">


    <style type="text/css">
        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }
      ion-icon{
        font-size: 30px;
      }
      body{
        /* background-color: rgb(255,248,240); */
      }
      .container{
        /* border: 1px solid black; */
      }
    </style>

</head>

<body class="bg-light">
    <div class="container">
        {% include 'navbar.html' %}
    </div>
    
    <!-- This code is for the image on a message -->
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="check-circle-fill" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
        <symbol id="info-fill" viewBox="0 0 16 16">
          <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
        </symbol>
        <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
          <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
    </svg>


    <div class="container">
        <div class="d-flex row justify-content-center align-items-center py-md-5 py-3", style="min-height: 70vh;">
            {% block content %}
            {% endblock content %}
        </div>
    </div>

    
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="facebook" viewBox="0 0 16 16">
            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
            </symbol>
            <symbol id="instagram" viewBox="0 0 16 16">
                <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
            </symbol>
            <symbol id="twitter" viewBox="0 0 16 16">
            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
            </symbol>
    </svg>

    <br><br><br>

    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/sidebars.js' %}"></script>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</body>
</html>

templates/navbar.html
{% load static %}
<!-- This is the navbar file     -->


<style type="text/css">
  .buttons{
    position: relative;
    top: 10px;
    display: flex;
    justify-content: space-between;
   }
   .buttons img{
    /* border: 1px solid black; */
   }
   .links{
    padding-top: 20px;
    /* border: 1px solid black; */
    /* margin-left: 349px; */
   }
   .links a{
    margin-left: 30px;
    text-decoration: none;
    color: rgb(103, 106, 109);
    position: relative;
   }
    .links a::after{
    content: '';
    width: 0;
    height: 3px;
    position: absolute;
    bottom: -5px;
    left: 50%;
    transform: translateX(-50%);
    background: black;
    transition: width 0.4s;
  }
  .links a:hover::after{
    width: 30px;
  }
  .logo-name{
    font-size: 40px;
    margin-bottom: -20px;
  }
  .logo{
    /* border: 1px solid black; */
  }
  .search{
    /* border: 1px solid black; */
    padding-top: 20px;
  }
  .search input{
    width: 400px;
  }
</style>


<div class="buttons">
  
  <div class="logo logo-name" >
    Press<img src="{% static 'assets/img/press logo.png' %}" alt="" style="width: 100px; height: 80px;" >Library
  </div>


  <div class="links">
    {% if request.user.is_authenticated %}
      <a href="{% url 'core:member_list' %}">Members</a>
      <a href="{% url 'core:book_list' %}">Books</a>
      <a href="{% url 'core:notification' %}">Notification</a>
      <a href="{% url 'core:profile' %}">Profile</a>
    {% else %}

    {% endif %}
  </div>

</div>

<br>